"""Naming of fresh generators for stable extensions.

The responsibility isolated here is deliberately narrow: given a polynomial
ring and a count, produce that many new generator names. Everything about
*when* to extend, and about keeping names reproducible across a whole
reduction sequence, belongs to the ``ReductionContext`` of version 0.2.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Protocol

import sympy as sp
from sympy.polys.rings import PolyRing

# Ein Name der Form Praefix + Index, etwa "x17" oder "X4".
_INDEXED_NAME = re.compile(r"(?P<prefix>[A-Za-z_][A-Za-z_]*)(?P<index>\d+)")

# Verwendet, wenn sich aus den vorhandenen Generatoren keine Konvention ablesen
# laesst. Entspricht dem Verhalten vor Einfuehrung der Factory.
FALLBACK_PREFIX = "X"


class VariableFactory(Protocol):
    """Produce fresh generator names for a ring.

    **A factory must be a pure function of its arguments.** Calling it twice
    with the same ring and the same count must yield the same names, and no
    call may influence a later one.

    This is not a matter of taste. Stable extension is a monoid homomorphism,

        (F o G)^[m] = F^[m] o G^[m],

    and the left and right hand sides reach ``extend`` through three separate
    calls. A factory that counts upwards would name the two sides differently
    and break the identity -- silently, because both sides remain perfectly
    valid polynomial maps. Anything that needs to remember something across
    calls belongs in a ``ReductionContext``, which is then responsible for
    handing the same factory to every side of such an identity.

    A factory is also responsible for avoiding collisions; see
    ``reserved_names``. ``PolynomialMap.extend`` rechecks the result rather
    than trusting it.

    **Extending twice must equal extending once.** Stable extension composes,

        (F^[m])^[l] = F^[m+l],

    so the names allocated by an extension of size ``m`` followed by one of
    size ``l`` must be exactly those allocated by a single extension of size
    ``m + l``, in that order.

    This does not follow from purity. A factory naming its output after the
    size of the ring it was handed -- ``g2_1, g2_2`` for a two-generator ring
    -- is perfectly pure and never collides, yet gives

        (F^[2])^[2] -> g2_1, g2_2, g4_1, g4_2
        F^[4]       -> g2_1, g2_2, g2_3, g2_4,

    two different maps where BCW needs one. Names must therefore be allocated
    from a sequence determined by the ring alone, with the count deciding only
    how far to walk it -- never entering the name itself.
    """

    def __call__(self, ring: PolyRing, count: int) -> tuple[sp.Symbol, ...]:
        """Return ``count`` symbols usable as new generators of ``ring``."""
        ...


def reserved_names(ring: PolyRing) -> frozenset[str]:
    """Return the names a fresh generator must not take.

    Generators of the ring itself, and symbols of the coefficient domain: an
    indeterminate ``T`` in ``k[T]`` is not a generator, but reusing its name
    would still collapse two distinct objects.
    """
    domain_symbols: tuple[object, ...] = tuple(getattr(ring.domain, "symbols", ()))

    return frozenset(
        symbol.name
        for symbol in tuple(ring.symbols) + domain_symbols
        if isinstance(symbol, sp.Symbol)
    )


@dataclass(frozen=True)
class IndexedVariableFactory:
    """Name new generators ``prefix1``, ``prefix2``, ... skipping taken names.

    Frozen and without state, so the purity requirement of
    ``VariableFactory`` holds by construction.

    With ``prefix=None`` the convention is read off the existing generators:
    a ring generated by ``x1, ..., x17`` is extended by ``x18, x19`` rather
    than by ``X18, X19``. Reductions compose many extensions, and a map whose
    coordinates are named in two competing schemes is needlessly hard to read
    against the paper. If the generators carry no such convention -- ``x, y``
    -- the fallback prefix is used.
    """

    prefix: str | None = None

    def __call__(self, ring: PolyRing, count: int) -> tuple[sp.Symbol, ...]:
        if count < 0:
            raise ValueError("The number of fresh variables must be non-negative.")

        taken = set(reserved_names(ring))
        prefix, index = self._convention(ring)

        fresh: list[sp.Symbol] = []
        while len(fresh) < count:
            name = f"{prefix}{index}"
            if name not in taken:
                fresh.append(sp.Symbol(name))
                taken.add(name)
            index += 1

        return tuple(fresh)

    def _convention(self, ring: PolyRing) -> tuple[str, int]:
        """Return the prefix to use and the index to start counting from."""
        if self.prefix is not None:
            return self.prefix, 1

        names = [
            symbol.name for symbol in ring.symbols if isinstance(symbol, sp.Symbol)
        ]
        matches = [_INDEXED_NAME.fullmatch(name) for name in names]

        if names and all(match is not None for match in matches):
            found = [match for match in matches if match is not None]
            prefixes = {match["prefix"] for match in found}
            if len(prefixes) == 1:
                return prefixes.pop(), max(int(match["index"]) for match in found) + 1

        return FALLBACK_PREFIX, ring.ngens + 1


DEFAULT_VARIABLE_FACTORY: VariableFactory = IndexedVariableFactory()
