"""Naming of fresh generators for stable extensions.

The responsibility isolated here is deliberately narrow: given a polynomial
ring and a count, produce that many new generator names. Everything about
*when* to extend, and about keeping names reproducible across a whole
reduction sequence, belongs to the ``ReductionContext`` of version 0.2.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Protocol

import sympy as sp
from sympy.polys.rings import PolyRing

# A name of the form prefix + index, for example "x17" or "X4".
_INDEXED_NAME = re.compile(r"(?P<prefix>[A-Za-z_][A-Za-z_]*)(?P<index>\d+)")

# Used when no convention can be read off the generators that are present.
# This matches the behaviour before the factory was introduced.
FALLBACK_PREFIX = "X"


class VariableFactory(Protocol):
    """Produce fresh generator names for a ring.

    **A factory must be a pure function of its arguments.** Calling it twice
    with the same ring and the same count must yield the same names, and no
    call may influence a later one.

    This is not a matter of taste. Stable extension is a monoid homomorphism,

        (F o G)^[m] = F^[m] o G^[m],

    and the left and right hand sides reach ``extend`` through three separate
    calls. A factory that counts upwards would name the two sides differently
    and break the identity -- silently, because both sides remain perfectly
    valid polynomial maps. Anything that needs to remember something across
    calls belongs in a ``ReductionContext``, which is then responsible for
    handing the same factory to every side of such an identity.

    A factory is also responsible for avoiding collisions; see
    ``reserved_names``. ``PolynomialMap.extend`` rechecks the result rather
    than trusting it.

    **Extending twice must equal extending once.** Stable extension composes,

        (F^[m])^[l] = F^[m+l],

    so the names allocated by an extension of size ``m`` followed by one of
    size ``l`` must be exactly those allocated by a single extension of size
    ``m + l``, in that order.

    This does not follow from purity. A factory naming its output after the
    size of the ring it was handed -- ``g2_1, g2_2`` for a two-generator ring
    -- is perfectly pure and never collides, yet gives

        (F^[2])^[2] -> g2_1, g2_2, g4_1, g4_2
        F^[4]       -> g2_1, g2_2, g2_3, g2_4,

    two different maps where BCW needs one. Names must therefore be allocated
    from a sequence determined by the ring alone, with the count deciding only
    how far to walk it -- never entering the name itself.
    """

    def __call__(self, ring: PolyRing, count: int) -> tuple[sp.Symbol, ...]:
        """Return ``count`` symbols usable as new generators of ``ring``."""
        ...


def domain_symbol_names(domain: Any) -> frozenset[str]:
    """Return the names of every indeterminate in ``domain``, at every level.

    Coefficient domains nest: over ``QQ[X3][S]`` the symbol ``S`` sits at the
    top and ``X3`` one level down. Looking only at ``domain.symbols`` finds
    ``S`` and misses ``X3``, which is enough for a stable extension to hand
    out a coordinate named ``X3`` and collapse it with the parameter.
    """
    names: set[str] = set()
    seen: set[int] = set()

    while domain is not None and domain.is_Composite and id(domain) not in seen:
        seen.add(id(domain))
        names.update(
            symbol.name
            for symbol in getattr(domain, "symbols", ())
            if isinstance(symbol, sp.Symbol)
        )
        domain = getattr(domain, "dom", None)

    return frozenset(names)


def reserved_names(ring: PolyRing) -> frozenset[str]:
    """Return the names a fresh generator must not take.

    Generators of the ring itself, and every indeterminate of the coefficient
    domain however deeply nested: a ``T`` in ``k[T]`` is not a generator, but
    reusing its name would still collapse two distinct objects.
    """
    generator_names = frozenset(
        symbol.name for symbol in ring.symbols if isinstance(symbol, sp.Symbol)
    )

    return generator_names | domain_symbol_names(ring.domain)


@dataclass(frozen=True)
class IndexedVariableFactory:
    """Name new generators ``prefix1``, ``prefix2``, ... skipping taken names.

    Frozen and without state, so the purity requirement of
    ``VariableFactory`` holds by construction.

    With ``prefix=None`` the convention is read off the existing generators:
    a ring generated by ``x1, ..., x17`` is extended by ``x18, x19`` rather
    than by ``X18, X19``. Reductions compose many extensions, and a map whose
    coordinates are named in two competing schemes is needlessly hard to read
    against the paper. If the generators carry no such convention -- ``x, y``
    -- the fallback prefix is used.
    """

    prefix: str | None = None

    def __call__(self, ring: PolyRing, count: int) -> tuple[sp.Symbol, ...]:
        if count < 0:
            raise ValueError("The number of fresh variables must be non-negative.")

        taken = set(reserved_names(ring))
        prefix, index = self._convention(ring)

        fresh: list[sp.Symbol] = []
        while len(fresh) < count:
            name = f"{prefix}{index}"
            if name not in taken:
                fresh.append(sp.Symbol(name))
                taken.add(name)
            index += 1

        return tuple(fresh)

    def _convention(self, ring: PolyRing) -> tuple[str, int]:
        """Return the prefix to use and the index to start counting from."""
        if self.prefix is not None:
            return self.prefix, 1

        names = [
            symbol.name for symbol in ring.symbols if isinstance(symbol, sp.Symbol)
        ]
        matches = [_INDEXED_NAME.fullmatch(name) for name in names]

        if names and all(match is not None for match in matches):
            found = [match for match in matches if match is not None]
            prefixes = {match["prefix"] for match in found}
            if len(prefixes) == 1:
                return prefixes.pop(), max(int(match["index"]) for match in found) + 1

        return FALLBACK_PREFIX, ring.ngens + 1


@dataclass(frozen=True)
class FixedVariableFactory:
    """Return names decided in advance, ignoring the ring.

    Constant, so purity holds trivially: it cannot count, and it cannot depend
    on what it is handed. It exists so that an extension can be pinned to names
    that are already fixed elsewhere -- a supplied certificate names the
    generators it used, and those have to be honoured rather than reinvented.

    It does *not* satisfy the composition requirement of ``VariableFactory``:
    asked for a count it was not built for, it raises rather than walking a
    sequence. That is deliberate. A factory for one extension of a known size
    belongs in ``PolynomialMap.extend``; a chain of extensions needs one that
    composes, which is what ``ReductionContext`` requires of its own.
    """

    names: tuple[sp.Symbol, ...]

    def __call__(self, ring: PolyRing, count: int) -> tuple[sp.Symbol, ...]:
        """Return the fixed names, if that is the number asked for."""
        if count != len(self.names):
            raise ValueError(
                f"This factory names {len(self.names)} generators, asked for {count}."
            )

        return self.names


DEFAULT_VARIABLE_FACTORY: VariableFactory = IndexedVariableFactory()
