"""Elementary automorphisms and the group ``EA_n(k)`` they generate.

Two objects, because BCW need two things. ``ElementaryFactor`` is a single
generator, invertible by an explicit formula. ``ElementaryAutomorphism`` is an
element of ``EA_n(k)``, stored as the ordered product of the factors that
build it -- the group is not generated by one factor, and Proposition (3.1)
uses products.

The factorization is kept rather than multiplied out. It is what makes an
inverse available without solving anything, and it is the part a certificate
has to exhibit: "invertible" is a claim, "here are the generators and their
inverses" is a proof.
"""

from __future__ import annotations

import math
from collections.abc import Iterable
from dataclasses import dataclass
from functools import cached_property
from typing import cast

import sympy as sp
from sympy.polys.polyerrors import CoercionFailed
from sympy.polys.rings import PolyElement, PolyRing

from .polynomial_map import PolynomialMap, clone_ring, copy_polynomial


@dataclass(frozen=True, eq=False)
class ElementaryFactor:
    """A generator of ``EA_n(k)``.

    BCW, p. 304: ``F`` in ``MA_n(k)`` is elementary if for some ``j`` the
    difference ``F_i - X_i`` vanishes for ``i != j`` and is independent of
    ``X_j`` for ``i = j``. So

        X_j  |-->  X_j + P,      P free of X_j,

    with no coefficient on ``X_j``. The paper draws the inverse straight from
    the definition, ``(F^-1)_i - X_i = -(F_i - X_i)``, that is

        X_j  |-->  X_j - P,

    and ``P`` survives the substitution unchanged precisely because it does
    not involve ``X_j``.

    A scaling ``X_j |-> a X_j + P`` with ``a != 1`` is a polynomial
    automorphism, but not an elementary one: its displacement ``(a - 1) X_j``
    depends on ``X_j``. Admitting it here would put elements of determinant
    other than one into ``EA_n(k)``, and the argument that a reduction step
    preserves the Jacobian determinant rests on every element of ``EA_n(k)``
    having determinant one. Scalings belong to the linear part, which
    Section 4 handles separately.

    Parameters
    ----------
    ring
        The arithmetic context. A factor acts on maps over the same ring.
    index
        The coordinate that moves.
    polynomial
        ``P``, as a SymPy expression or an element of ``ring``.
    """

    _ring: PolyRing
    _index: int
    _polynomial: PolyElement

    def __init__(
        self,
        ring: PolyRing,
        index: int,
        polynomial: sp.Expr | PolyElement,
    ) -> None:
        if isinstance(index, bool) or not isinstance(index, int):
            raise TypeError(
                f"The index must be an integer, not {type(index).__name__}."
            )

        if not 0 <= index < ring.ngens:
            raise ValueError(
                f"Index {index} is out of range for {ring.ngens} variables."
            )

        element = self._coerce_polynomial(ring, polynomial)

        if any(monomial[index] for monomial in element.itermonoms()):
            raise ValueError(
                f"The polynomial must not involve {ring.symbols[index]}; "
                "otherwise the factor is not invertible by the elementary formula."
            )

        owned = clone_ring(ring)

        object.__setattr__(self, "_ring", owned)
        object.__setattr__(self, "_index", index)
        object.__setattr__(self, "_polynomial", copy_polynomial(element, owned))

    @staticmethod
    def _coerce_polynomial(
        ring: PolyRing, polynomial: sp.Expr | PolyElement
    ) -> PolyElement:
        if isinstance(polynomial, PolyElement):
            if not ring.is_element(polynomial):
                raise ValueError("The polynomial must belong to the specified ring.")
            return polynomial

        try:
            return ring.from_expr(polynomial)
        except (ValueError, CoercionFailed) as error:
            raise ValueError(
                "The polynomial must be a polynomial over the specified ring."
            ) from error

    # ----------------------------------------------------------------------
    # Inspection
    # ----------------------------------------------------------------------

    @cached_property
    def _view_ring(self) -> PolyRing:
        """A value-equal clone of the internal ring, for handing out."""
        return clone_ring(self._ring)

    @property
    def ring(self) -> PolyRing:
        """Return the arithmetic context of the factor.

        A clone, for the reason given at ``PolynomialMap.ring``: a
        ``PolyRing`` owns mutable generators, and SymPy reads them.
        """
        return self._view_ring

    @property
    def index(self) -> int:
        """Return the coordinate that moves."""
        return self._index

    @property
    def variable(self) -> sp.Symbol:
        """Return the variable that moves."""
        return cast(sp.Symbol, self._ring.symbols[self._index])

    @property
    def polynomial(self) -> sp.Expr:
        """Return ``P`` as an immutable SymPy expression."""
        return cast(sp.Expr, self._polynomial.as_expr())

    # ----------------------------------------------------------------------
    # Group structure
    # ----------------------------------------------------------------------

    def inverse(self) -> ElementaryFactor:
        """Return the inverse factor, read off the definition rather than solved.

        BCW state it directly: ``(F^-1)_i - X_i = -(F_i - X_i)``.
        """
        return ElementaryFactor(
            ring=self._ring,
            index=self._index,
            polynomial=-self._polynomial,
        )

    def determinant(self) -> sp.Expr:
        """Return the Jacobian determinant, which is one.

        Structural, and a theorem rather than a computation: the Jacobian is
        the identity except for row ``i``, whose off-diagonal entries are the
        partials of ``P`` and whose diagonal entry is one, because ``P`` does
        not involve ``X_i``. The matrix is unipotent.

        A reduction step rests on this. It is also why a scaling factor has no
        place in the class: it would break the property for the whole group.
        """
        return cast(sp.Expr, sp.Integer(1))

    def apply_to(self, other: PolynomialMap) -> PolynomialMap:
        """Return ``self o other``.

        Only one coordinate changes, so one polynomial composition suffices
        instead of ``n`` -- the reason this class exists rather than everything
        being a ``PolynomialMap``.
        """
        if self._ring != other.ring:
            raise ValueError("The factor and the map use different rings.")

        components = list(other.to_polynomials())
        substitution = dict(zip(self._ring.gens, components, strict=True))

        components[self._index] = components[self._index] + self._polynomial.compose(
            substitution
        )

        return PolynomialMap.from_ring(self._ring, components)

    def to_polynomial_map(self) -> PolynomialMap:
        """Return the factor as a ``PolynomialMap``."""
        components = list(self._ring.gens)
        components[self._index] = components[self._index] + self._polynomial
        return PolynomialMap.from_ring(self._ring, components)

    # ----------------------------------------------------------------------
    # Filtration
    # ----------------------------------------------------------------------

    def order(self) -> int | float:
        """Return ``ord(E - X)``, which is ``ord(P)``.

        The displacement has the single nonzero component ``P``, so no map has
        to be formed.
        """
        return min(
            (sum(monomial) for monomial in self._polynomial.itermonoms()),
            default=math.inf,
        )

    def filtration_degree(self) -> int | float:
        """Return the largest ``d`` with the factor in ``EA^d``."""
        return self.order() - 1

    def is_in_EA(self, d: int) -> bool:  # noqa: N802
        """Return whether the factor lies in ``EA^d``."""
        return self.filtration_degree() >= d

    # ----------------------------------------------------------------------

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, ElementaryFactor):
            return NotImplemented
        return (
            self._ring.symbols == other._ring.symbols
            and self._ring.domain == other._ring.domain
            and self._index == other._index
            and self.polynomial == other.polynomial
        )

    def __hash__(self) -> int:
        return hash(
            (self._ring.symbols, self._ring.domain, self._index, self.polynomial)
        )

    def __repr__(self) -> str:
        return (
            f"ElementaryFactor(variable={self.variable}, polynomial={self.polynomial})"
        )


@dataclass(frozen=True, eq=False)
class ElementaryAutomorphism:
    """An element of ``EA_n(k)``, as an ordered product of factors.

    ``factors = (f_1, ..., f_k)`` denotes ``f_1 o ... o f_k``. The empty
    product is the identity.

    Two different factorizations of the same automorphism are different
    objects here, and compare unequal, even though their ``PolynomialMap``s
    agree. That is deliberate: the factorization is the certificate, and a
    reduction step has to exhibit the one it used.
    """

    factors: tuple[ElementaryFactor, ...]

    def __init__(self, factors: Iterable[ElementaryFactor] = ()) -> None:
        collected = tuple(factors)

        if not all(isinstance(factor, ElementaryFactor) for factor in collected):
            raise TypeError("All factors must be ElementaryFactor instances.")

        rings = {factor.ring for factor in collected}
        if len(rings) > 1:
            raise ValueError("All factors must use the same ring.")

        object.__setattr__(self, "factors", collected)

    @classmethod
    def identity(cls) -> ElementaryAutomorphism:
        """Return the empty product."""
        return cls(())

    @property
    def ring(self) -> PolyRing:
        """Return the shared arithmetic context of the factors."""
        if not self.factors:
            raise ValueError("The identity carries no ring.")
        return self.factors[0].ring

    # ----------------------------------------------------------------------
    # Group structure
    # ----------------------------------------------------------------------

    def compose(self, other: ElementaryAutomorphism) -> ElementaryAutomorphism:
        """Return ``self o other``, by concatenating the factorizations."""
        if self.factors and other.factors and self.ring != other.ring:
            raise ValueError("The automorphisms use different rings.")

        return ElementaryAutomorphism(self.factors + other.factors)

    def inverse(self) -> ElementaryAutomorphism:
        """Return the inverse, ``(f_1 o ... o f_k)^-1 = f_k^-1 o ... o f_1^-1``."""
        return ElementaryAutomorphism(
            factor.inverse() for factor in reversed(self.factors)
        )

    def determinant(self) -> sp.Expr:
        """Return the Jacobian determinant, which is one.

        Every generator of ``EA_n(k)`` has determinant one, so every element
        does. This is why ``BCWStep.verify`` can afford a determinant check at
        every step: for the elementary parts there is nothing to compute.
        """
        return cast(sp.Expr, sp.Integer(1))

    def apply_to(self, other: PolynomialMap) -> PolynomialMap:
        """Return ``self o other``.

        Applied right to left, one factor at a time, so no intermediate full
        map composition is ever formed.
        """
        result = other
        for factor in reversed(self.factors):
            result = factor.apply_to(result)
        return result

    def to_polynomial_map(self, ring: PolyRing | None = None) -> PolynomialMap:
        """Return the product as a ``PolynomialMap``.

        ``ring`` is required only for the identity, which carries none.
        """
        context = self.ring if self.factors else ring
        if context is None:
            raise ValueError("The identity needs a ring to become a map.")

        identity = PolynomialMap.from_ring(context, context.gens)
        return self.apply_to(identity)

    # ----------------------------------------------------------------------
    # Filtration
    # ----------------------------------------------------------------------

    def filtration_degree(self) -> int | float:
        """Return the largest ``d`` with the automorphism in ``EA^d``.

        Unlike the determinant this does not follow from the factors: a
        product of factors in ``EA^0`` can land in ``EA^1``, so the map has to
        be formed. ``MA^d`` being a submonoid gives a lower bound only.

        The empty product is the identity, which lies in every ``EA^d`` and
        carries no ring to form a map from.
        """
        if not self.factors:
            return math.inf

        return self.to_polynomial_map().filtration_degree()

    def is_in_EA(self, d: int) -> bool:  # noqa: N802
        """Return whether the automorphism lies in ``EA^d``."""
        return self.filtration_degree() >= d

    # ----------------------------------------------------------------------

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, ElementaryAutomorphism):
            return NotImplemented
        return self.factors == other.factors

    def __hash__(self) -> int:
        return hash(self.factors)

    def __len__(self) -> int:
        return len(self.factors)

    def __repr__(self) -> str:
        return f"ElementaryAutomorphism(factors={self.factors})"
