"""Elementary automorphisms and the group ``EA_n(k)`` they generate.

Two objects, because BCW need two things. ``ElementaryFactor`` is a single
generator, invertible by an explicit formula. ``ElementaryAutomorphism`` is an
element of ``EA_n(k)``, stored as the ordered product of the factors that
build it -- the group is not generated by one factor, and Proposition (3.1)
uses products.

The factorization is kept rather than multiplied out. It is what makes an
inverse available without solving anything, and it is the part a certificate
has to exhibit: "invertible" is a claim, "here are the generators and their
inverses" is a proof.
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from typing import Any, cast

import sympy as sp
from sympy.polys.polyerrors import CoercionFailed, ExactQuotientFailed
from sympy.polys.rings import PolyElement, PolyRing

from .polynomial_map import PolynomialMap, copy_polynomial


@dataclass(frozen=True, eq=False)
class ElementaryFactor:
    """A generator of ``EA_n(k)``.

    The map fixing every coordinate but one,

        X_i  |-->  a * X_i + P,

    with ``a`` a unit of the coefficient domain and ``P`` free of ``X_i``.
    Both conditions are what make the inverse explicit,

        X_i  |-->  a^-1 * (X_i - P),

    and ``P`` is unchanged by the substitution precisely because it does not
    involve ``X_i``.

    Parameters
    ----------
    ring
        The arithmetic context. A factor acts on maps over the same ring.
    index
        The coordinate that moves.
    polynomial
        ``P``, as a SymPy expression or an element of ``ring``.
    coefficient
        ``a``. Defaults to one, which is the case BCW use throughout.
    """

    _ring: PolyRing
    _index: int
    _coefficient: Any
    _polynomial: PolyElement

    def __init__(
        self,
        ring: PolyRing,
        index: int,
        polynomial: sp.Expr | PolyElement,
        coefficient: sp.Expr | int = 1,
    ) -> None:
        if not 0 <= index < ring.ngens:
            raise ValueError(
                f"Index {index} is out of range for {ring.ngens} variables."
            )

        element = self._coerce_polynomial(ring, polynomial)

        if any(monomial[index] for monomial in element.itermonoms()):
            raise ValueError(
                f"The polynomial must not involve {ring.symbols[index]}; "
                "otherwise the factor is not invertible by the elementary formula."
            )

        unit = self._coerce_unit(ring, coefficient)

        object.__setattr__(self, "_ring", ring)
        object.__setattr__(self, "_index", index)
        object.__setattr__(self, "_coefficient", unit)
        object.__setattr__(self, "_polynomial", copy_polynomial(element))

    @staticmethod
    def _coerce_polynomial(
        ring: PolyRing, polynomial: sp.Expr | PolyElement
    ) -> PolyElement:
        if isinstance(polynomial, PolyElement):
            if not ring.is_element(polynomial):
                raise ValueError("The polynomial must belong to the specified ring.")
            return polynomial

        try:
            return ring.from_expr(polynomial)
        except (ValueError, CoercionFailed) as error:
            raise ValueError(
                "The polynomial must be a polynomial over the specified ring."
            ) from error

    @staticmethod
    def _coerce_unit(ring: PolyRing, coefficient: sp.Expr | int) -> Any:
        """Return ``coefficient`` as an invertible element of the domain.

        The check is against the domain the map actually lives in, not against
        some field it could be embedded into. A map built from integer
        coefficients has domain ``ZZ``, where the only units are +-1; BCW work
        over a field, so a map that needs a scaling factor has to be built
        over one.
        """
        domain = ring.domain

        try:
            element = domain.from_sympy(sp.sympify(coefficient))
        except CoercionFailed as error:
            raise ValueError(
                f"The coefficient must lie in the coefficient domain {domain}."
            ) from error

        try:
            domain.exquo(domain.one, element)
        except (ExactQuotientFailed, ZeroDivisionError) as error:
            raise ValueError(
                f"The coefficient {coefficient} is not invertible in {domain}."
            ) from error

        return element

    # ----------------------------------------------------------------------
    # Inspection
    # ----------------------------------------------------------------------

    @property
    def ring(self) -> PolyRing:
        """Return the arithmetic context of the factor."""
        return self._ring

    @property
    def index(self) -> int:
        """Return the coordinate that moves."""
        return self._index

    @property
    def variable(self) -> sp.Symbol:
        """Return the variable that moves."""
        return cast(sp.Symbol, self._ring.symbols[self._index])

    @property
    def polynomial(self) -> sp.Expr:
        """Return ``P`` as an immutable SymPy expression."""
        return cast(sp.Expr, self._polynomial.as_expr())

    @property
    def coefficient(self) -> sp.Expr:
        """Return ``a`` as an immutable SymPy expression."""
        return cast(sp.Expr, self._ring.domain.to_sympy(self._coefficient))

    # ----------------------------------------------------------------------
    # Group structure
    # ----------------------------------------------------------------------

    def inverse(self) -> ElementaryFactor:
        """Return the inverse factor, by formula rather than by solving."""
        domain = self._ring.domain
        reciprocal = domain.exquo(domain.one, self._coefficient)

        return ElementaryFactor(
            ring=self._ring,
            index=self._index,
            polynomial=-self._polynomial * reciprocal,
            coefficient=domain.to_sympy(reciprocal),
        )

    def determinant(self) -> sp.Expr:
        """Return the Jacobian determinant, which is ``a``.

        Structural: the Jacobian is the identity except for row ``i``, whose
        diagonal entry is ``a``. No polynomial arithmetic is involved, which
        is what lets a reduction check determinants at every step.
        """
        return self.coefficient

    def apply_to(self, other: PolynomialMap) -> PolynomialMap:
        """Return ``self o other``.

        Only one coordinate changes, so one polynomial composition suffices
        instead of ``n`` -- the reason this class exists rather than everything
        being a ``PolynomialMap``.
        """
        if self._ring != other.ring:
            raise ValueError("The factor and the map use different rings.")

        components = list(other.to_polynomials())
        substitution = dict(zip(self._ring.gens, components, strict=True))

        components[self._index] = components[
            self._index
        ] * self._coefficient + self._polynomial.compose(substitution)

        return PolynomialMap.from_ring(self._ring, components)

    def to_polynomial_map(self) -> PolynomialMap:
        """Return the factor as a ``PolynomialMap``."""
        components = list(self._ring.gens)
        components[self._index] = (
            components[self._index] * self._coefficient + self._polynomial
        )
        return PolynomialMap.from_ring(self._ring, components)

    # ----------------------------------------------------------------------
    # Filtration
    # ----------------------------------------------------------------------

    def order(self) -> int | float:
        """Return ``ord(E - X)``.

        Computed on the one component that moves. The displacement is
        ``(a - 1) X_i + P``, so a factor with ``a != 1`` has order at most one
        however deep ``P`` sits.
        """
        displacement = (
            self._polynomial
            + (self._coefficient - self._ring.domain.one) * self._ring.gens[self._index]
        )
        return min(
            (sum(monomial) for monomial in displacement.itermonoms()),
            default=float("inf"),
        )

    def filtration_degree(self) -> int | float:
        """Return the largest ``d`` with the factor in ``EA^d``."""
        return self.order() - 1

    def is_in_EA(self, d: int) -> bool:  # noqa: N802
        """Return whether the factor lies in ``EA^d``."""
        return self.filtration_degree() >= d

    # ----------------------------------------------------------------------

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, ElementaryFactor):
            return NotImplemented
        return (
            self._ring.symbols == other._ring.symbols
            and self._index == other._index
            and self.coefficient == other.coefficient
            and self.polynomial == other.polynomial
        )

    def __hash__(self) -> int:
        return hash(
            (self._ring.symbols, self._index, self.coefficient, self.polynomial)
        )

    def __repr__(self) -> str:
        return (
            f"ElementaryFactor(variable={self.variable}, "
            f"coefficient={self.coefficient}, polynomial={self.polynomial})"
        )


@dataclass(frozen=True, eq=False)
class ElementaryAutomorphism:
    """An element of ``EA_n(k)``, as an ordered product of factors.

    ``factors = (f_1, ..., f_k)`` denotes ``f_1 o ... o f_k``. The empty
    product is the identity.

    Two different factorizations of the same automorphism are different
    objects here, and compare unequal, even though their ``PolynomialMap``s
    agree. That is deliberate: the factorization is the certificate, and a
    reduction step has to exhibit the one it used.
    """

    factors: tuple[ElementaryFactor, ...]

    def __init__(self, factors: Iterable[ElementaryFactor] = ()) -> None:
        collected = tuple(factors)

        if not all(isinstance(factor, ElementaryFactor) for factor in collected):
            raise TypeError("All factors must be ElementaryFactor instances.")

        rings = {factor.ring for factor in collected}
        if len(rings) > 1:
            raise ValueError("All factors must use the same ring.")

        object.__setattr__(self, "factors", collected)

    @classmethod
    def identity(cls) -> ElementaryAutomorphism:
        """Return the empty product."""
        return cls(())

    @property
    def ring(self) -> PolyRing:
        """Return the shared arithmetic context of the factors."""
        if not self.factors:
            raise ValueError("The identity carries no ring.")
        return self.factors[0].ring

    # ----------------------------------------------------------------------
    # Group structure
    # ----------------------------------------------------------------------

    def compose(self, other: ElementaryAutomorphism) -> ElementaryAutomorphism:
        """Return ``self o other``, by concatenating the factorizations."""
        if self.factors and other.factors and self.ring != other.ring:
            raise ValueError("The automorphisms use different rings.")

        return ElementaryAutomorphism(self.factors + other.factors)

    def inverse(self) -> ElementaryAutomorphism:
        """Return the inverse, ``(f_1 o ... o f_k)^-1 = f_k^-1 o ... o f_1^-1``."""
        return ElementaryAutomorphism(
            factor.inverse() for factor in reversed(self.factors)
        )

    def determinant(self) -> sp.Expr:
        """Return the Jacobian determinant, the product of the coefficients.

        This is why ``BCWStep.verify`` can afford a determinant check: for the
        elementary factors it is a product of scalars, not an expansion.
        """
        result = sp.Integer(1)
        for factor in self.factors:
            result *= factor.coefficient
        return cast(sp.Expr, result)

    def apply_to(self, other: PolynomialMap) -> PolynomialMap:
        """Return ``self o other``.

        Applied right to left, one factor at a time, so no intermediate full
        map composition is ever formed.
        """
        result = other
        for factor in reversed(self.factors):
            result = factor.apply_to(result)
        return result

    def to_polynomial_map(self, ring: PolyRing | None = None) -> PolynomialMap:
        """Return the product as a ``PolynomialMap``.

        ``ring`` is required only for the identity, which carries none.
        """
        context = self.ring if self.factors else ring
        if context is None:
            raise ValueError("The identity needs a ring to become a map.")

        identity = PolynomialMap.from_ring(context, context.gens)
        return self.apply_to(identity)

    # ----------------------------------------------------------------------
    # Filtration
    # ----------------------------------------------------------------------

    def filtration_degree(self) -> int | float:
        """Return the largest ``d`` with the automorphism in ``EA^d``.

        Unlike the determinant this does not follow from the factors: a
        product of factors in ``EA^0`` can land in ``EA^1``, so the map has to
        be formed. ``MA^d`` being a submonoid gives a lower bound only.
        """
        return self.to_polynomial_map().filtration_degree()

    def is_in_EA(self, d: int) -> bool:  # noqa: N802
        """Return whether the automorphism lies in ``EA^d``."""
        return self.filtration_degree() >= d

    # ----------------------------------------------------------------------

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, ElementaryAutomorphism):
            return NotImplemented
        return self.factors == other.factors

    def __hash__(self) -> int:
        return hash(self.factors)

    def __len__(self) -> int:
        return len(self.factors)

    def __repr__(self) -> str:
        return f"ElementaryAutomorphism(factors={self.factors})"
