from __future__ import annotations

import math
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from functools import cached_property
from graphlib import CycleError, TopologicalSorter
from typing import cast

import sympy as sp
from sympy.polys.matrices import DomainMatrix
from sympy.polys.polyerrors import PolynomialError
from sympy.polys.rings import PolyElement, PolyRing, sring

from .variables import (
    DEFAULT_VARIABLE_FACTORY,
    VariableFactory,
    reserved_names,
)

# Eine Matrix duenn besetzter Polynome, zeilenweise.
Block = tuple[tuple["PolyElement", ...], ...]


def _names_are_distinct(symbols: Iterable[sp.Symbol]) -> bool:
    """Return whether no two symbols share a name.

    Names, not symbols: two ``Symbol`` objects carrying different assumptions
    compare unequal but print identically, and a ring generated by both has
    two generators that no expression can tell apart.
    """
    names = [symbol.name for symbol in symbols]
    return len(set(names)) == len(names)


@dataclass(frozen=True, eq=False)
class PolynomialMap:
    """A polynomial endomorphism of an affine space.

    The public boundary uses SymPy expressions, while polynomial arithmetic is
    performed internally in a sparse :class:`~sympy.polys.rings.PolyRing`.

    Parameters
    ----------
    variables
        Pairwise distinct generators of the polynomial ring.
    components
        Polynomial coordinate functions in ``variables``. Symbols not listed
        in ``variables`` are placed in the coefficient domain.
    """

    _ring: PolyRing
    _poly_components: tuple[PolyElement, ...]

    def __init__(
        self, variables: Iterable[sp.Symbol], components: Iterable[sp.Expr]
    ) -> None:
        variables_tuple = tuple(variables)
        components_tuple = tuple(components)

        self._validate_expr_input(variables_tuple, components_tuple)

        try:
            polynomial_ring, polynomial_components = sring(
                components_tuple, *variables_tuple
            )
        except PolynomialError as exc:
            raise ValueError(
                "Components must be polynomials in the specified variables."
            ) from exc

        object.__setattr__(self, "_ring", polynomial_ring)
        object.__setattr__(
            self,
            "_poly_components",
            tuple(
                self._copy_polynomial(polynomial)
                for polynomial in polynomial_components
            ),
        )

    @classmethod
    def from_ring(
        cls,
        polynomial_ring: PolyRing,
        components: Iterable[PolyElement],
    ) -> PolynomialMap:
        """Construct a map directly from elements of ``polynomial_ring``.

        This is the efficient construction path for internal algorithms. The
        components are copied so that the immutable ``PolynomialMap`` does not
        share mutable ``PolyElement`` instances with its caller.
        """
        components_tuple = tuple(components)

        if not polynomial_ring.ngens:
            raise ValueError("A polynomial map needs at least one variable.")

        if not all(isinstance(symbol, sp.Symbol) for symbol in polynomial_ring.symbols):
            raise TypeError("Ring generators must be SymPy symbols.")

        if not _names_are_distinct(polynomial_ring.symbols):
            raise ValueError("Ring generators must be pairwise distinct.")

        if polynomial_ring.ngens != len(components_tuple):
            raise ValueError("Number of variables and components differ.")

        if not all(polynomial_ring.is_element(f) for f in components_tuple):
            raise ValueError("All components must belong to the specified ring.")

        instance = object.__new__(cls)
        object.__setattr__(instance, "_ring", polynomial_ring)
        object.__setattr__(
            instance,
            "_poly_components",
            tuple(cls._copy_polynomial(component) for component in components_tuple),
        )
        return instance

    @staticmethod
    def _copy_polynomial(polynomial: PolyElement) -> PolyElement:
        """Recursively copy a polynomial and polynomial coefficients."""
        terms = []
        for monomial, coefficient in polynomial.iterterms():
            if isinstance(coefficient, PolyElement):
                coefficient = PolynomialMap._copy_polynomial(coefficient)
            terms.append((monomial, coefficient))
        return polynomial.ring.from_terms(terms)

    @staticmethod
    def _validate_expr_input(
        variables: tuple[sp.Symbol, ...],
        components: tuple[sp.Expr, ...],
    ) -> None:
        """Validate the expression-level constructor arguments."""
        if not variables:
            raise ValueError("A polynomial map needs at least one variable.")

        if len(variables) != len(components):
            raise ValueError("Number of variables and components differ.")

        if not all(isinstance(variable, sp.Symbol) for variable in variables):
            raise TypeError("Variables must be SymPy symbols.")

        if not _names_are_distinct(variables):
            raise ValueError("Variables must be pairwise distinct.")

        if not all(isinstance(component, sp.Expr) for component in components):
            raise TypeError("Components must be SymPy expressions.")

    @property
    def ring(self) -> PolyRing:
        """Return the internal sparse polynomial ring.

        The returned ring is the arithmetic context. Coordinate polynomials
        remain private because ``PolyElement`` is mutable.
        """
        return self._ring

    @property
    def variables(self) -> tuple[sp.Symbol, ...]:
        """Return the polynomial variables."""
        return cast(tuple[sp.Symbol, ...], self._ring.symbols)

    @cached_property
    def components(self) -> tuple[sp.Expr, ...]:
        """Return the coordinate functions as immutable SymPy expressions."""
        return tuple(component.as_expr() for component in self._poly_components)

    def to_polynomials(self) -> tuple[PolyElement, ...]:
        """Return defensive copies of the internal coordinate polynomials."""
        return tuple(
            self._copy_polynomial(component) for component in self._poly_components
        )

    @property
    def dimension(self) -> int:
        """Return the dimension of the polynomial endomorphism."""
        return int(self._ring.ngens)

    @cached_property
    def matrix(self) -> sp.ImmutableMatrix:
        """Return the components as an expression-valued column matrix.

        Immutable, and not by convention only: the result is cached, so a
        mutable matrix handed out here would let a caller alter the value of
        every later evaluation. ``sp.Matrix(F.matrix)`` yields a mutable copy
        where one is wanted.
        """
        return sp.ImmutableMatrix(self.components)

    @cached_property
    def _jacobian_polynomials(self) -> tuple[tuple[PolyElement, ...], ...]:
        return tuple(
            tuple(component.diff(variable) for variable in self._ring.gens)
            for component in self._poly_components
        )

    def jacobian(self) -> sp.ImmutableMatrix:
        """Return the Jacobian matrix as SymPy expressions.

        Built afresh on each call, so mutability could not corrupt any state
        here. Immutable for consistency with the rest of the public boundary,
        which promises immutable SymPy objects throughout.
        """
        return sp.ImmutableMatrix(
            [[entry.as_expr() for entry in row] for row in self._jacobian_polynomials]
        )

    # ----------------------------------------------------------------------
    # Jacobian determinant
    # ----------------------------------------------------------------------

    @cached_property
    def carrier_indices(self) -> tuple[int, ...]:
        """Return coordinates spanning a unipotent block of the Jacobian.

        An index ``i`` qualifies when ``dF_i/dX_i == 1`` and the dependencies
        among the qualifying coordinates are acyclic. The induced block is
        then ``I + L`` with ``L`` nilpotent, because an acyclic dependency
        graph makes ``L`` permutation-similar to a strictly triangular matrix.

        Stable extensions and elementary automorphisms produce exactly this
        shape, so BCW-reduced maps carry a large unipotent block by
        construction. The result is a valid, not necessarily maximal, such
        set: breaking a cycle drops every coordinate on it.
        """
        rows = self._jacobian_polynomials
        one = self._ring.one

        candidates = {
            index for index in range(self.dimension) if rows[index][index] == one
        }

        while candidates:
            try:
                TopologicalSorter(self._dependency_graph(candidates)).prepare()
            except CycleError as error:
                candidates -= set(error.args[1])
            else:
                break

        return tuple(sorted(candidates))

    def _dependency_graph(self, indices: Iterable[int]) -> dict[int, set[int]]:
        """Return, for each of ``indices``, the others it differentiates against."""
        rows = self._jacobian_polynomials
        index_set = set(indices)

        return {
            index: {
                other for other in index_set if other != index and rows[index][other]
            }
            for index in index_set
        }

    def _is_unipotent_block(self, indices: Sequence[int]) -> bool:
        """Return whether ``J[indices, indices]`` is ``I + L`` with ``L`` nilpotent.

        Nilpotency is decided on the dependency graph, not by taking powers:
        an acyclic graph orders the block strictly triangular, so ``L`` raised
        to the block size vanishes. That is a boolean test on monomial
        supports and costs no polynomial arithmetic.
        """
        rows = self._jacobian_polynomials

        if not all(rows[index][index] == self._ring.one for index in indices):
            return False

        try:
            TopologicalSorter(self._dependency_graph(indices)).prepare()
        except CycleError:
            return False

        return True

    def _determinant_by_domain_matrix(self, block: Block) -> PolyElement:
        """Return ``det(block)`` over the sparse polynomial-ring domain.

        The empty matrix has determinant one; ``DomainMatrix`` does not
        accept it.
        """
        if not block:
            return self._ring.one

        matrix = DomainMatrix.from_list(
            [list(row) for row in block],
            self._ring.to_domain(),
        )
        return cast(PolyElement, matrix.det())

    def _schur_complement(self, carrier: Sequence[int]) -> Block | None:
        """Return ``A - B D^-1 C`` for the split induced by ``carrier``.

        With ``D = I + L`` unipotent, the block determinant formula

            det J = det(D) * det(A - B D^-1 C) = det(A - B D^-1 C)

        replaces an ``n x n`` determinant by one of size ``n - len(carrier)``.

        Only ``D^-1 C`` is formed, never ``D^-1``: the Neumann series
        ``sum_k (-L)^k C`` keeps every intermediate result as narrow as the
        head block.

        ``None`` signals that ``carrier`` does not induce a unipotent block.
        The precondition is checked here and not merely inherited from
        ``carrier_indices``, because the identity above needs ``det(D) = 1``.
        Terminating the series is not evidence for that: with an empty head
        block the series terminates immediately whatever ``L`` is, and the
        empty Schur complement would then claim determinant one for a map
        whose determinant is anything at all.
        """
        if not self._is_unipotent_block(carrier):
            return None

        rows = self._jacobian_polynomials
        carrier_set = set(carrier)
        head = tuple(i for i in range(self.dimension) if i not in carrier_set)

        displacement = tuple(
            tuple(
                rows[i][j] - self._ring.one if i == j else rows[i][j] for j in carrier
            )
            for i in carrier
        )
        lower_right = tuple(tuple(rows[i][j] for j in head) for i in carrier)

        # L^len(carrier) = 0 by the precondition, so the loop always breaks.
        solution = lower_right
        term = lower_right
        for _ in range(len(carrier)):
            term = self._negated_product(displacement, term)
            if not any(entry for row in term for entry in row):
                break
            solution = tuple(
                tuple(a + b for a, b in zip(left, right, strict=True))
                for left, right in zip(solution, term, strict=True)
            )

        upper_right = tuple(tuple(rows[i][j] for j in carrier) for i in head)
        correction = self._product(upper_right, solution)

        return tuple(
            tuple(rows[i][j] - entry for j, entry in zip(head, row, strict=True))
            for i, row in zip(head, correction, strict=True)
        )

    @staticmethod
    def _product(left: Block, right: Block) -> Block:
        """Return the matrix product, computed on sparse polynomials."""
        if not left or not right:
            return tuple(() for _ in left)

        width = len(right[0])
        return tuple(
            tuple(
                sum(
                    (row[k] * right[k][j] for k in range(len(right))),
                    right[0][0].ring.zero,
                )
                for j in range(width)
            )
            for row in left
        )

    @classmethod
    def _negated_product(cls, left: Block, right: Block) -> Block:
        return tuple(
            tuple(-entry for entry in row) for row in cls._product(left, right)
        )

    @cached_property
    def _determinant_polynomial(self) -> PolyElement:
        carrier = self.carrier_indices

        if carrier:
            schur_complement = self._schur_complement(carrier)
            if schur_complement is not None:
                return self._determinant_by_domain_matrix(schur_complement)

        return self._determinant_by_domain_matrix(self._jacobian_polynomials)

    def determinant(self) -> sp.Expr:
        """Return the Jacobian determinant.

        The determinant is computed over the sparse polynomial-ring domain,
        not through an expression-valued SymPy matrix.

        Where the Jacobian has a unipotent block -- which BCW-reduced maps
        always do -- the computation is reduced to the Schur complement of
        that block. An elementary automorphism is unipotent throughout, so
        its determinant is one by structure rather than by expansion.
        """
        return self._determinant_polynomial.as_expr()

    def compose(self, other: PolynomialMap) -> PolynomialMap:
        """Return the simultaneous composition ``self ∘ other``."""
        if self.variables != other.variables:
            raise ValueError("Polynomial maps have different variables.")

        left, right, common_ring = self._coerce_to_common_ring(other)
        substitutions = dict(zip(common_ring.gens, right, strict=True))
        components = tuple(component.compose(substitutions) for component in left)

        return PolynomialMap.from_ring(common_ring, components)

    def _coerce_to_common_ring(
        self, other: PolynomialMap
    ) -> tuple[
        tuple[PolyElement, ...],
        tuple[PolyElement, ...],
        PolyRing,
    ]:
        """Return both maps in one compatible polynomial ring."""
        if self._ring == other._ring:
            return self._poly_components, other._poly_components, self._ring

        expressions = self.components + other.components
        common_ring, common_components = sring(expressions, *self.variables)
        split = self.dimension
        return (
            tuple(common_components[:split]),
            tuple(common_components[split:]),
            common_ring,
        )

    def degree(self) -> int:
        """Return the largest total degree of a coordinate function."""
        return max(
            (
                sum(monomial)
                for component in self._poly_components
                for monomial in component.itermonoms()
            ),
            default=0,
        )

    def order(self) -> int | float:
        """Return the smallest occurring total degree.

        The order of the zero map is ``math.inf``.
        """
        return min(
            (
                sum(monomial)
                for component in self._poly_components
                for monomial in component.itermonoms()
            ),
            default=math.inf,
        )

    def displacement(self) -> PolynomialMap:
        """Return ``F - X``."""
        components = tuple(
            component - variable
            for component, variable in zip(
                self._poly_components, self._ring.gens, strict=True
            )
        )
        return PolynomialMap.from_ring(self._ring, components)

    def filtration_degree(self) -> int | float:
        """Return the largest ``d`` such that the map lies in ``MA^d``."""
        return self.displacement().order() - 1

    def is_in_MA(self, d: int) -> bool:  # noqa: N802
        """Return whether the map lies in ``MA^d``."""
        return self.filtration_degree() >= d

    def extend(
        self,
        number: int = 2,
        factory: VariableFactory | None = None,
    ) -> PolynomialMap:
        """Extend the map by ``number`` identity coordinates.

        ``factory`` names the new generators; see
        :class:`~bcw.variables.VariableFactory` for the purity requirement it
        must satisfy. Passing one explicitly is how an identity such as

            (F o G)^[m] = F^[m] o G^[m]

        states that all three extensions share a naming policy, instead of
        relying on equal-dimensional maps happening to agree.
        """
        if number < 0:
            raise ValueError("The extension size must be non-negative.")
        if number == 0:
            return self

        make_variables = DEFAULT_VARIABLE_FACTORY if factory is None else factory
        new_variables = make_variables(self._ring, number)
        self._validate_fresh_variables(new_variables, number)

        new_ring = self._ring.clone(symbols=self.variables + new_variables)
        old_components = tuple(
            component.set_ring(new_ring) for component in self._poly_components
        )
        components = old_components + new_ring.gens[-number:]
        return PolynomialMap.from_ring(new_ring, components)

    def _validate_fresh_variables(
        self, fresh: tuple[sp.Symbol, ...], number: int
    ) -> None:
        """Check what a factory promised but is not trusted to have delivered.

        A colliding name would not raise anywhere downstream: ``clone`` would
        accept it and produce a ring in which two coordinates silently denote
        the same generator.
        """
        if len(fresh) != number:
            raise ValueError(
                f"The variable factory returned {len(fresh)} names, expected {number}."
            )

        if not all(isinstance(symbol, sp.Symbol) for symbol in fresh):
            raise TypeError("The variable factory must return SymPy symbols.")

        if len(set(fresh)) != len(fresh):
            raise ValueError("The variable factory returned duplicate names.")

        collisions = {symbol.name for symbol in fresh} & reserved_names(self._ring)
        if collisions:
            raise ValueError(
                "The variable factory returned names already in use: "
                f"{sorted(collisions)}."
            )

    def __call__(self, *args: sp.Expr) -> sp.ImmutableMatrix:
        """Evaluate the map, allowing arbitrary symbolic arguments."""
        if len(args) != self.dimension:
            raise ValueError(f"Expected {self.dimension} arguments, got {len(args)}.")

        substitutions = dict(zip(self.variables, args, strict=True))
        return self.matrix.xreplace(substitutions)

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, PolynomialMap):
            return NotImplemented
        return self.variables == other.variables and self.components == other.components

    def __hash__(self) -> int:
        return hash((self.variables, self.components))

    def __repr__(self) -> str:
        return (
            f"PolynomialMap(variables={self.variables}, components={self.components})"
        )
